#!/bin/sh
XMLTV_TYPE="FILE"
XMLTV_LOCATION_FILE=""
XMLTV_LOCATION_WEB=""

dflag=
vflag=
cflag=

if [ $# -lt 1 ]; then

  if [ "$XMLTV_TYPE" = "FILE" ]; then

    
    cat "$XMLTV_LOCATION_FILE"
    exit 0

  elif [ "$XMLTV_TYPE" = "WEB" ]; then
    wget -qO - "$XMLTV_LOCATION_WEB"
    exit 0
  fi
fi

for arg; do
    delim=""
    case "$arg" in
    #translate --gnu-long-options to -g (short options)
       --description) args="${args}-d ";;
       --version) args="${args}-v ";;
       --capabilities) args="${args}-c ";;
       #pass through anything else
       *) [[ "${arg:0:1}" == "-" ]] || delim="\""
           args="${args}${delim}${arg}${delim} ";;
    esac
done

#Reset the positional parameters to the short options
eval set -- $args

while getopts "dvc" option; do
    case $option in
        d)  dflag=1;;
        v)  vflag=1;;
        c)  cflag=1;;
        \?) echo "unknown option: -%s\n" $OPTARG
            echo "Usage: %s: [--description] [--version] [--capabilities] \n" $(basename $0)
            exit 2
            ;;
    esac >&2
done

if [ "$dflag" ]; then
   echo "tv_grab_movistar-guiniguada - Grabber EPG-GUINIGUADA--Movistar TV"
fi
if [ "$vflag" ]; then
   echo "0.1\n"
fi
if [ "$cflag" ]; then
   echo "baseline\n"
fi
